#!/bin/bash
set -e

# Parse options
OPTS=`getopt -o rt: --long release,tar:,grafana-api-key:,unsigned -n 'parse-options' -- "$@"`

if [ $? != 0 ] ; then
  echo "Failed parsing options." >&2
  exit 1
fi

eval set -- "$OPTS"

TARFILE=
GRAFANA_API_KEY=$(gcloud secrets versions access latest --secret=ci-grafana-api-key --project=digia-iiris-dev)
GRAFANA_ROOT_URLS="https://develop.digiaiiris.com/grafana/ https://digiaiiris.com/grafana/ https://sok.digiaiiris.com/grafana/ https://vayla.digiaiiris.com/grafana/ https://support.digiaiiris.com/grafana/ https://demo.digiaiiris.com/grafana/ https://test.digiaiiris.com/grafana/"

while true; do
  case "$1" in
    -r | --release ) TARFILE="iiris-zabbix-plugin.tar.gz"; shift;;
    -t | --tar ) TARFILE="$2"; shift 2;;
    -- ) shift; break ;;
    * ) break ;;
  esac
done

if [ -z "$GRAFANA_API_KEY" ]; then
  echo "ERROR: Grafana API key missing. API key must be exported in GRAFANA_API_KEY environment variable!"
  exit 1
fi

# Build
docker build . -f Dockerfile.iiris-build -t iiris-zabbix-plugin-build --build-arg=GRAFANA_API_KEY=$GRAFANA_API_KEY --build-arg=GRAFANA_ROOT_URLS="$GRAFANA_ROOT_URLS"

if [ ! -z "$TARFILE" ]; then
    docker run --rm -i --entrypoint sh iiris-zabbix-plugin-build -c "cat iiris-zabbix-plugin.tar.gz" >$TARFILE
fi
