export const texts = {
  fi: {
    critical: 'Kriittinen',
    major: 'Vakava',
    average: 'Keskitaso',
    minor: 'Matala',
    info: 'Informatiivinen',
    unknown: 'Tuntematon',
    noActiveAlerts: 'Ei aktiivisia häiriöitä',
    acknowledgeProblem: 'Kommentoi',
    time: 'Aika',
    user: 'Käyttäjä',
    comments: 'Kommentit',
    message: 'Viesti',
    pressEnterToSubmit: 'Paina Enter lähettääksesi',
    update: 'Päivitä',
    cancel: 'Peruuta',
    changeSeverity: 'Muuta prioriteettia',
    acknowledge: 'Merkitse käsitellyksi',
    closeProblem: 'Sulje häiriö',
    lastedFor: 'kestänyt',
    information: 'Tietoja',
    title: 'Otsikko',
    description: 'Kuvaus',
    priority: 'Prioriteetti',
    eventId: 'Häiriön ID',
    startTime: 'Alkamisaika',
    endTime: 'Päättymisaika',
    duration: 'Kesto',
    acknowledgements: 'Kommentit',
    dashboard: 'Tilannekuvanäkymä',
    urlInfo: 'Siirry määriteltyyn tilannekuvaan',
    search: 'Haku',
    selectCategory: 'Valitse kategoria',
    selectPriority: 'Valitse prioriteetti',
    testIncident: 'Testihäiriö',
    hideAlertsInMaintenance: 'Piilota huollon aikaiset häiriöt',
    sortBy: 'Lajitteluperuste',
    pieces: 'kpl',
  },
  en: {
    critical: 'Critical',
    major: 'Major',
    average: 'Average',
    minor: 'Minor',
    info: 'Informative',
    unknown: 'Unknown',
    noActiveAlerts: 'No active alerts',
    acknowledgeProblem: 'Acknowledge Problem',
    time: 'Time',
    user: 'User',
    comments: 'Comments',
    message: 'Message',
    pressEnterToSubmit: 'Press Enter to submit',
    update: 'Update',
    cancel: 'Cancel',
    changeSeverity: 'Change severity',
    acknowledge: 'Acknowledge',
    closeProblem: 'Close problem',
    lastedFor: 'lasted for',
    information: 'Information',
    title: 'Title',
    description: 'Description',
    priority: 'Priority',
    eventId: 'Event ID',
    startTime: 'Start time',
    endTime: 'End time',
    duration: 'Duration',
    acknowledgements: 'Acknowledgements',
    dashboard: 'Dashboard',
    urlInfo: 'Open defined dashboard',
    search: 'Search',
    selectCategory: 'Select category',
    selectPriority: 'Select priority',
    testIncident: 'Test Incident',
    hideAlertsInMaintenance: 'Hide alerts triggered during maintenance',
    sortBy: 'Sort by',
    pieces: 'pcs',
  },
};
