export const texts = {
  fi: {
    critical: 'Kriittinen',
    major: 'Vakava',
    average: 'Keskitaso',
    minor: 'Matala',
    info: 'Informatiivinen',
    unknown: 'Tuntematon',
    noActiveAlerts: 'Ei aktiivisia häiriöitä',
    acknowledgeProblem: 'Kommentoi',
    time: 'Aika',
    user: 'Käyttäjä',
    comments: 'Kommentit',
    message: 'Viesti',
    pressEnterToSubmit: 'Paina Enter lähettääksesi',
    update: 'Päivitä',
    cancel: 'Peruuta',
    changeSeverity: 'Muuta prioriteettia',
    acknowledge: 'Merkitse käsitellyksi',
    closeProblem: 'Sulje häiriö',
  },
  en: {
    critical: 'Critical',
    major: 'Major',
    average: 'Average',
    minor: 'Minor',
    info: 'Informative',
    unknown: 'Unknown',
    noActiveAlerts: 'No active alerts',
    acknowledgeProblem: 'Acknowledge Problem',
    time: 'Time',
    user: 'User',
    comments: 'Comments',
    message: 'Message',
    pressEnterToSubmit: 'Press Enter to submit',
    update: 'Update',
    cancel: 'Cancel',
    changeSeverity: 'Change severity',
    acknowledge: 'Acknowledge',
    closeProblem: 'Close problem',
  },
};
