{
 "title": "Zabbix Template Linux Server",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "group", "label": "Group", "query": "*" },
   { "name": "host", "label": "Host", "query": "$group.*" },
   { "name": "netif", "label": "Network interface", "query": "*.$host.Network interfaces.*" }
  ]
 },
 "panels": [
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "application": { "filter": "CPU" },
     "evaltype": "0",
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "/CPU/" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "minSeverity": 3,
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "System load",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "application": { "filter": "CPU" },
     "evaltype": "0",
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "Processor load (15 min average per core)"
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "minSeverity": 3,
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Network traffic on $netif",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "repeat": "netif",
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "/$netif/" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "minSeverity": 3,
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  }
 ]
}